---
inherit_gem:
  dox-best-practices: .rubocop.yml
  dox-style:
  - ".rubocop.yml"

Env/OutsideConfig:
  Exclude:
    - "./tasks/ci.rake"

Env/UndefinedVar:
  Exclude:
    - "./tasks/ci.rake"

Env/UseFetch:
  Exclude:
    - "./bin/*"

Metrics/BlockLength:
  Exclude:
    - "./**/*_spec.rb"
    - "./*.gemspec"
    - "./spec/*_helper*.rb"
    - "./tasks/ci.rake"
    - "Gemfile"

Metrics/ClassLength:
  Exclude:
    - "./**/*_spec.rb"

Metrics/AbcSize:
  Exclude:
    - "./**/*_spec.rb"

Metrics/ModuleLength:
  Exclude:
    - "./**/*_spec*.rb"

Metrics/MethodLength:
  Exclude:
    - "./**/*_spec.rb"

Style/ClassAndModuleChildren:
  Exclude:
    - "./**/*.rb"
